{% set name = "Corrfunc" %}
{% set version = "2.4.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 7fd177ba245c5aeb3ea5c2006f071a1c6134736d9b25530bd46b321162e7335a
  patches:
    - 00000_nonative_common.mk.patch

build:
  number: 2
  script: {{ PYTHON }} -m pip install . -vv --install-option="CC=${CC}"
  skip: true  # [win]

requirements:
  build:
    - {{ compiler('c') }}
    - make >=3.80
    - llvm-openmp  # [osx]
    - libgomp      # [linux]
  host:
    - python
    - pip
    - numpy
    - libcblas
    - gsl
  run:
    - python
    - {{ pin_compatible('numpy') }}
    - wurlitzer
    - future

test:
  imports:
    - Corrfunc

about:
  home: https://github.com/manodeep/Corrfunc
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Blazing fast correlation functions on the CPU
  doc_url: http://corrfunc.readthedocs.io/

extra:
  recipe-maintainers:
    - beckermr
