{% set name = "Corrfunc" %}
{% set version = "2.5.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 1138a49e2c9be60bf8394cf4abbe2849c21e8ee02fca222e2eab5f2589d8a509
  patches:
    - 00000_nonative_common.mk.patch

build:
  number: 0
  script: {{ PYTHON }} -m pip install . -vv --global-option="CC=${CC}"
  skip: true  # [win]

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - numpy                                  # [build_platform != target_platform]
    - {{ compiler('c') }}
    - make >=3.80
    - llvm-openmp  # [osx]
    - libgomp      # [linux]
  host:
    - python
    - pip
    - numpy
    - libcblas
    - gsl
  run:
    - python
    - {{ pin_compatible('numpy') }}
    - wurlitzer
    - future

test:
  imports:
    - Corrfunc

about:
  home: https://github.com/manodeep/Corrfunc
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Blazing fast correlation functions on the CPU
  doc_url: http://corrfunc.readthedocs.io/

extra:
  recipe-maintainers:
    - beckermr
