{% set name = "Corrfunc" %}
{% set version = "2.3.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: beaa3f96316f5fca94ddfe7052bd860c0170057b73d43a575e00cbd103bd1036

build:
  number: 1
  script: '{{ PYTHON }} -m pip install . -vv --install-option="CC=${CC}"'
  skip: True  # [win]

requirements:
  build:
    - {{ compiler('c') }}
    - make >=3.80
  host:
    - python
    - pip
    - numpy
    - libcblas
    - gsl >=2.4
    - llvm-openmp  # [osx]
  run:
    - python
    - {{ pin_compatible('numpy') }}
    - llvm-openmp  # [osx]
    - wurlitzer
    - future

test:
  imports:
    - Corrfunc

about:
  home: https://github.com/manodeep/Corrfunc
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: 'Blazing fast correlation functions on the CPU'
  doc_url: http://corrfunc.readthedocs.io/

extra:
  recipe-maintainers:
    - beckermr
